name: Update README with GitHub Stats

on:
  schedule:
    - cron: '0 * * * *' # This cron job runs every hour
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch GitHub Stats
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_STATS_SECRET }}
      run: |
        stats=$(curl -s "https://github-readme-stats.vercel.app/api?username=timwhite06&show_icons=true&count_private=true&theme=dark&include_all_commits=true&token=${ACCESS_TOKEN}")
        langs=$(curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=timwhite06&layout=compact&theme=dark&count_private=true&token=${ACCESS_TOKEN}")
        echo "Fetched GitHub Stats:"
        echo "$stats"
        echo "Fetched Languages:"
        echo "$langs"
        sed -i 's|<!-- STATS_PLACEHOLDER -->|![GitHub Stats](https://github-readme-stats.vercel.app/api?username=timwhite06&show_icons=true&count_private=true&theme=dark&include_all_commits=true&token='${ACCESS_TOKEN}')|g' README.md
        sed -i 's|<!-- LANGS_PLACEHOLDER -->|![Most Used Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=timwhite06&layout=compact&theme=dark&count_private=true&token='${ACCESS_TOKEN}')|g' README.md

    - name: Commit Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git diff --cached
        git commit -m "Update GitHub stats"
        git push
